req_extensions = v3_req # The extensions to add to a certificate request
prompt = no

[v3_req]
# Extensions to add to a certificate request
basicConstraints 	= critical, CA:FALSE
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always, issuer:always
keyUsage	 	= critical, nonRepudiation, digitalSignature, keyEncipherment, keyAgreement
extendedKeyUsage   	= critical, serverAuth
subjectAltName 		= @alt_names

[alt_names]
DNS.1 = leonpc.asuscomm.com
DNS.2 = leonnote.asuscomm.com
DNS.3 = SI1374.asuscomm.com
DNS.4 = *.asuscomm.com
DNS.5 = localhost
IP.1  = 127.0.0.1
IP.2  = 192.168.134.114
IP.3  = 192.168.134.127
IP.4  = 192.168.134.140
IP.5  = 172.24.96.1
IP.6  = 10.0.2.2
